#!/bin/sh

# A dmenu wrapper script for system functions.

# For non-systemd init systems.
case "$(readlink -f /sbin/init)" in
	*runit*) hib="sudo -A zzz" ;;
	*openrc*) reb="sudo -A openrc-shutdown -r"; shut="sudo -A openrc-shutdown -p" ;;
esac

cmds="\
 lock		slock
 leave leftwm 	loginctl kill-session $XDG_SESSION_ID 2>&1 >/dev/null
 renew leftwm 	 leftwm-command SoftReload
 standby	slock ${hib:-systemctl suspend}
 reboot	${reb:-sudo -A reboot}
 shutdown	${shut:-sudo -A shutdown -h now}"

# 🐻 standbay	slock ${hib:-systemctl suspend -i}
choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
