#!/bin/sh
get_icon() {
    case $1 in
        # Icons for emoji
        01d) icon="🌞";;
        01n) icon="🌞";;
        02d) icon="🌤";;
        02n) icon="🌤";;
        03*) icon="🌥";;
        04*) icon="☁";;
        09d) icon="🌧";;
        09n) icon="🌧";;
        10d) icon="🌦";;
        10n) icon="🌦";;
        11d) icon="🌩";;
        11n) icon="🌩";;
        13d) icon="🌨";;
        13n) icon="🌨";;
        50d) icon="🌫";;
        50n) icon="🌫";;
        *) icon="🐱";

        # Icons for weather-icons

        # 01d) icon="";;
        # 01n) icon="";;
        # 02d) icon="";;
        # 02n) icon="";;
        # 03*) icon="";;
        # 04*) icon="";;
        # 09d) icon="";;
        # 09n) icon="";;
        # 10d) icon="";;
        # 10n) icon="";;
        # 11d) icon="";;
        # 11n) icon="";;
        # 13d) icon="";;
        # 13n) icon="";;
        # 50d) icon="";;
        # 50n) icon="";;
        # *) icon="";

        # Icons for Font Awesome 5 Pro
        #01d) icon="";;
        #01n) icon="";;
        #02d) icon="";;
        #02n) icon="";;
        #03d) icon="";;
        #03n) icon="";;
        #04*) icon="";;
        #09*) icon="";;
        #10d) icon="";;
        #10n) icon="";;
        #11*) icon="";;
        #13*) icon="";;
        #50*) icon="";;
        #*) icon="";
    esac

    echo $icon
}

KEY="d3bbbac74bc0d5aba7e664387bf7fb55"
CITY="1795565"
# CITY="1812896"
UNITS="metric"
SYMBOL="°"
weather=$'\0'

API="https://api.openweathermap.org/data/2.5"

# wget -q --spider example.org || exit
# echo ""
if [ -n "$CITY" ]; then
    if [ "$CITY" -eq "$CITY" ] 2>/dev/null; then
        CITY_PARAM="id=$CITY"
    else
        CITY_PARAM="q=$CITY"
    fi

    COUNTER=0
    while [ $COUNTER -lt 10 ] && [ -z "$weather" ];do
        weather=$(curl -sf "$API/weather?appid=$KEY&$CITY_PARAM&units=$UNITS")
        sleep 10
        let COUNTER=COUNTER+1
    done
else
    location=$(curl -sf https://location.services.mozilla.com/v1/geolocate?key=geoclue)

    if [ -n "$location" ]; then
        location_lat="$(echo "$location" | jq '.location.lat')"
        location_lon="$(echo "$location" | jq '.location.lng')"

        weather=$(curl -sf "$API/weather?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS")
    fi
fi

if [ -n "$weather" ]; then
    weather_temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
    weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")

    echo "$(get_icon "$weather_icon")"" $weather_temp$SYMBOL " > "${XDG_DATA_HOME:-$HOME/.local/share}/weatherup.tmp"
    # eww update eww_weather="$(get_icon "$weather_icon")"" $weather_temp$SYMBOL "
else
    # eww update eww_weather="Service not available"
    echo "Service not available" > "${XDG_DATA_HOME:-$HOME/.local/share}/weatherup.tmp"
fi
# polybar-msg hook weather 1 2>&1 > /dev/null
