#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

if [ $(uname -n) = "lenovo-t480" ]; then
  if [ `ifconfig wlan0 | awk '/inet /{ print $6;}'` = "192.168.186.255" ]; then
      source ~/.xrandr &
      # nextcloud --background &
      # run autorandr -l docked
  fi
fi

if [ -x /usr/bin/gpg-agent ]; then
    eval "$(/usr/bin/gpg-agent --daemon)"
fi

# source .xrandr
# ssh-agent dwm
exec dbus-launch leftwm
# exec dbus-launch bspwm
# ssh-agent leftwm
# exec dbus-launch `ssh-agent leftwm`
# exec dbus-launch --exit-with-session `ssh-agent leftwm`
# exec /usr/bin/startplasma-x11
