#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
if [ $(hostname) == "XMLaptop" ]; then
#	echo "ok"
	source ~/.xrandr
	nextcloud &
fi
#mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
 wallpaper.sh &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
#xcompmgr &		# xcompmgr for transparency
picom -f -b
dunst &			# dunst for notifications
#xset r rate 400 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
fcitx5 &
# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and

# 	pidof -s ! pidof -s pulseaudio >/dev/null 2>&1 &&
# 	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
