#!/bin/sh

function run {
  if (command -v $1 && ! pgrep $1); then
    $@&
  fi
}

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
if [ $(hostname) = "XMLaptop" ]; then
  if [ `ifconfig wlp2s0 | awk '/inet /{ print $6;}'` = "192.168.186.255" ]; then
      # echo "ok"
      source ~/.xrandr
      run nextcloud --background
  fi
	# nextcloud &
  # blueman-applet &
fi
#mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg ~/Pictures/wallpaper &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
# run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# run eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg)
#xcompmgr &		# xcompmgr for transparency
picom -f -b --experimental-backends
# picom -f -b
dunst &			# dunst for notifications
xset r rate 400 50 # Speed xrate up
unclutter &		# Remove mouse when idle
fcitx5 &
# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and

# 	pidof -s ! pidof -s pulseaudio >/dev/null 2>&1 &&
# 	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
