[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty --class kitty-dropterm"
animation = "fromBottom"
margin = 10
unfocus = "hide"
size = "50% 85%"
position = "49% 150px"
max_size = "1920px 100%"
