#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

. $SCRIPTPATH/autostart.sh

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# start eww daemon
eww daemon --debug & 

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends &> /dev/null &
  # picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi
dunst &
# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
# if [ -x "$(command -v feh)" ]; then
#   feh --bg-scale $SCRIPTPATH/background.jpg
# fi
#open eww 'bar' windows
#this is a bit of an uggly hack, a more elegant way will hopefully be possible with a future `eww` version
# sleep 1
# while [[ -z "$(eww windows | grep '[*]')" ]]; do
#     index=0
#     sizes=( $(leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' ) )
#     for size in "${sizes[@]}"
#     do
#         eww open bar$index
#         let index=index+1
#     done
#   # eww open-many left tags right
# done
# for size in "${sizes[@]}"
# do
#     eww open bar$index
#   let index=index+1
# done
if [ $(hostname) = "XMLaptop" ]; then
    eww open bar0
    sleep 10
    eww reload
fi

if [ $(uname -n) = "lenovo-t480" ]; then
    eww close-all
    eww open-many bar0 bar1
fi

if [ $(uname -n) = "lenovo-pc" ]; then
    eww close-all
    sleep 10
    eww open bar0
fi

