#! /bin/sh
gap=15
PANEL_HEIGHT=25
export gap
export PANEL_HEIGHT
export DESKTOP_SESSION="bspwm"

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# We look for a non-laptop monitor to use for default, but use the laptop screen
# (LVSD) if there is nothing else. This is because I assume that if you have an
# extra screen attached to a laptop, you want to use that.

#mainmonitor="$(bspc query --monitors --names | grep -v eDP1 | head -n 1)"

mainmonitor="$(bspc query --monitors --names | grep -v eDP1 | head -n 1)"
#mainmonitor="eDP1"
if [ -z $mainmonitor ]; then
	mainmonitor="eDP1"
fi

#if ! echo "$mainmonitor" | grep eDP1 > /dev/null 2>&1; then
#	xrandr --output "$mainmonitor" --auto --output eDP1 --off
#else
#	xrandr --output eDP1 --auto
#fi
autorandr --change

# Start workspaces on the main monitor.
bspc monitor $mainmonitor -d 1 2 3 4 5 6 7
bspc desktop -f 1

# If you want a multi-monitor display or something else, I leave that to you to
# arrange. I have this sensible default for most people's use cases.


#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap
bspc config top_padding $(($PANEL_HEIGHT-$gap))
bspc config left_padding $gap
bspc config right_padding $gap
bspc config bottom_padding $gap

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config single_monocle true
#bspc config ignore_ewmh_focus      true
bspc config initial_polarity second_child
bspc config automatic_scheme longest_side
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true

##Color settings
bspc config focused_border_color "#7D2CC3"
bspc config normal_border_color "#2D2D2D"
#"#000000"
bspc config presel_feedback_color "#1ABB9B"
#"#8F3724"
bspc config border_width 2

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false #Some keybindings automatically enable and disable this setting
bspc config click_to_focus any
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#Settings for manual splitting
bspc config split_ratio         0.5

#bspc monitor -d i ii iii iv v vi vii viii ix x
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d • • • • • • • • • •
#bspc monitor -d I II III IV V VI

#if [ $(hostname) = "tramhao-pc" ]; then
#	bspc monitor eDP1 -d I II III IV V VI VII
#elif [ $(hostname) = "XMLaptop" ]; then
#	xrandr --output DP1 --primary --mode 1920x1200 \
#		--pos 0x0 --rotate normal --output eDP1 --off --output HDMI2 --auto
#	bspc monitor DP1 -d I II III IV V VI VII
#	bspc monitor eDP1 -d I II III IV V VI VII
#	bspc monitor HDMI2 -d I II III IV V VI VII
#fi


###This creates and names desktops for multiple monitors.
#workspaces_multimonitor &



bspc rule -a screenkey --unmanage
bspc rule -a gcolor2 state=floating center=true
bspc rule -a lxappearance state=floating center=true
bspc rule -a gmrun state=floating center=true
bspc rule -a lxterminal state=floating center=true sticky=true
#bspc rule -a urxvt state=floating center=true
bspc rule -a viewnior state=floating center=true
bspc rule -a file-roller state=floating center=true
bspc rule -a floaterm state=floating center=true
bspc rule -a spotify state=pseudo_tiled
#bspc rule -a nautilus state=pseudo_tiled
#bspc rule -a skype state=pseudo_tiled
bspc rule -a file-roller state=pseudo_tiled
bspc rule -a transmission-gtk state=pseudo_tiled
bspc rule -a conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a yad state=floating
bspc rule -a Docky layer=above border=off manage=on
bspc rule -a Plank layer=above border=off manage=on
bspc rule -a wbar layer=above
bspc rule -a dockbarx layer=above
bspc rule -a google-chrome-unstable private=on
bspc rule -a google-chrome-stable private=on
#bspc rule -a chromium private=on
#bspc rule -a Chromium desktop=II follow=on
bspc rule -a Brave-browser private=on
bspc rule -a Brave-browser desktop=2 follow=on
bspc rule -a midori private=on
bspc rule -a gnome-pie border=off manage=off
bspc rule -a wpa_gui state=pseudo_tiled
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
#bspc rule -a firefox desktop=I
#bspc rule -a calibre desktop=II
#bspc rule -a geany desktop=II
#bspc rule -a deluge desktop=III
bspc rule -a 9menu border=off manage=off
bspc rule -a tint2 border=off manage=off
#bspc desktop I --layout monocle
#bspc desktop II --layout monocle
bspc rule -a Gimp desktop=4 state=floating follow=on
bspc rule -a Darktable desktop=5 follow=on
bspc rule -a Oblogout state=floating center=true private=on
bspc rule -a dolphin desktop=3 follow=on
#bspc rule -a scratchpad state=floating
bspc rule -a Pavucontrol state=floating

##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
#autogap &

##  This script balances all windows when new one is spawned
#euclid_balancer &

##Edge-switcher switches to next workspace when moves moves to the
##edge of the monitor (behavior similar to enlightenment)
#edge-switcher &

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window

##Autostart apps
#Keybindings daemon
#killall sxhkd
#sxhkd &
#killall compton
#compton -b &
#killall ibus-daemon
#ibus-daemon -drx &
#killall polkit-gnome-authentication-agent-1
#killall gnome-keyring-daemon
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
#killall feh
#feh --bg-fill ~/.scripts/pix/wall2.jpg &
#nextcloud &
#sleep 1
#Source autostartfile. Uncomment this if you use bspwm-git
#. $HOME/.config/bspwm/autostart
#limepanel &


source $HOME/.config/bspwm/autostart.sh
sleep 2

#killall polybar
# if [ $(hostname) = "tramhao-pc" ]; then
# 	        $HOME/.config/polybar/launch2.sh &
# elif [ $(hostname) = "XMLaptop" ]; then
# 	        $HOME/.config/polybar/launch.sh &
# else
$HOME/.config/polybar/launch.sh &
# fi

#ntfd &
#dropdownname="dropdown"
#bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
#bspc rule -a St:$dropdownname hidden=on
#bspc rule -a St:$dropdownname sticky=on
#bspc rule -a St:$dropdownname state=floating

#bspc config external_rules_command "$(which floaters)"

#killall nm-applet
#nm-applet &
#killall variety
#variiety &

#st -c scratchterm &

#bspc rule -a scratchterm sticky=on state=floating hidden=on

#bspwm swallow
bspc subscribe node_add node_remove \
	        | grep -o --line-buffered '0x[0-9A-F]\+$' | xargs -n1 pidswallow &
