border_width = 3
margin = 5 
workspace_margin = [5,0,5,0] 
default_border_color = "#37474F"
floating_border_color = "#22ff55"
focused_border_color = "#FFB53A"

[[gutter]]
side = "Left"
value = 20
wsid = 0

[[gutter]]
side = "Right"
value = 20
wsid = 0
