#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $USER)/bus; export DISPLAY=:0; . $HOME/.zprofile; 
. $SCRIPTPATH/autostart.sh

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down


# boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom -f -b --experimental-backends &> /dev/null & 
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
# if [ -x "$(command -v feh)" ]; then
#   feh --bg-scale "${SCRIPTPATH}/background.jpg"
# fi
# export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $USER)/bus; export DISPLAY=:0; . $HOME/.zprofile; setbg $HOME/Pictures/wallpapers
#make sure all fonts needed are installed
${SCRIPTPATH}/fonts/install_fonts

# extra utils to make this theme a little more homey
if [ -x "$(command -v dunst)" ]; then
  dunst &
fi

#boot a polybar for each monitor
polybar-msg cmd quit

export DEFAULT_NETWORK_INTERFACE=$(ip route | grep '^default' | awk '{print $5}' | head -n1)

if [ $(uname -n) = "lenovo-pc" ]; then
    export DEFAULT_NETWORK_INTERFACE=enp3s0
fi

cd ${SCRIPTPATH}/polybar
# polybar -m | sed s/:.*// | tac | while read -r monitor
  for m in $(polybar --list-monitors | cut -d":" -f1); do
    # monitor=$m polybar -c config.ini main --reload > /dev/null 2> /tmp/polybar_leftwm$m.log &
    monitor=$m polybar -c config.ini main --reload 2>&1 | tee -a /tmp/polybar_leftwm$m.log & disown
  done
# do 
#   # monitor=$monitor polybar -c config.ini main &> /dev/null &
#   monitor=$monitor polybar -c config.ini main &> /tmp/polybar_leftwm.log &
#   # monitor=$monitor polybar -c config.ini main 2> /tmp/polybar_leftwm.log &
# done

