theme = "monokai_pro_machine"
# theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
j = { k = "normal_mode" }


