[[language]]
name = "python"
# scope = "source.python"
# language-server = { command = "ruff-lsp" }
# config = { settings = { args = [] } }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "markdown"
language-server = { command = "/home/tramhao/.local/share/cargo/bin/mdpls" }
config = { markdown.preview.auto = true, markdown.preview.browser = "brave" }

[[language]]
name = "rust"
roots = ["Cargo.lock",".github"]
